name: Piper
on:
  workflow_dispatch:

jobs:
  piper:
    uses: "project-piper/piper-pipeline-github/.github/workflows/sap-piper-workflow.yml@v1"
    secrets: inherit
    permissions:
      contents: write
      id-token: write
